baseURL = "https://blog.ritimgitar.com/"
languageCode = "de-DE"
title = "Distributed Thoughts"
theme = "cactus"
copyright = "Baris Goral" # 
publishDir = "docs"
googleAnalytics = "UA-187005043-1"


# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3



[params]
  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  description = ">\"People who deny the existence of dragons are often eaten by dragons. From within.\" Ursula K Le Guin"
  mainSection = "posts" # your main section
  tagsOverview = true
  showAllPostsOnHomePage = true # default
 # postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  dateFormat = "2006-01-02" # default
  css = ["css/custom.css"]

 